"""initial migration

Revision ID: 5f04716ef767
Revises: 
Create Date: 2024-07-29 22:31:39.853336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f04716ef767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_frequency', sa.Enum('ONCE_A_WEEK', 'ONCE_EVERY_TWO_WEEKS', 'ONCE_A_MONTH', name='recurrencefrequency'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('recurrence_frequency')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
